name: CD

on:
  push:
    branches: [main]

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - uses: actions/setup-node@v3
        with:
            node-version: 18
            cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Pushing to production
        run: pnpm dlx vercel --prod --token=${{ secrets.VERCEL_TOKEN }}
