name: CI

on:
  pull_request:
    types: [opened, synchronize]

env:
  SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
  SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
  SUPABASE_SECRET: ${{ secrets.SUPABASE_SECRET }}

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - uses: actions/setup-node@v3
        with:
            node-version: 18
            cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Running lint
        run: pnpm --filter main... lint

  test:
    name: Test
    runs-on: ubuntu-latest
    container: cypress/browsers:node18.12.0-chrome107

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - uses: actions/setup-node@v3
        with:
            node-version: 18
            cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Running cypress
        run: pnpm --filter main... test
